# Flash sections are mapped into both flash banks, YOLO
[[flash]]
address = 0x08000000
size = 2097152
read = true
execute = true

# RAM sections are currently mapped into DTCM, a small but fast SRAM.
[[ram]]
address = 0x20000000
size = 131072
read = true
write = true
execute = false  # let's assume XN until proven otherwise

# Network buffers are placed in sram1, which is directly accessible by the
# Ethernet MAC.
[[sram1]]
address = 0x30000000
size = 0x20000
read = true
write = true
dma = true

