[package]
name = "drv-nrf52-gpio-common"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = {path = "../../../sys/userlib"}
num-traits = {version = "0.2", default-features = false}
zerocopy = "0.6.1"
