name = "demo-nrf52840-feather"
target = "thumbv7em-none-eabihf"
board = "nrf52840-feather"
chip = "../../chips/nRF52840.toml"
stacksize = 896

[kernel]
path = "."
name = "demo-nrf52840-feather"
requires = {flash = 60000, ram = 3072}
features = ["itm"]

[supervisor]
notification = 1

[outputs.flash]
address = 0x0000_0000
size = 0x0010_0000
read = true
execute = true

[outputs.ram]
address = 0x2000_0000
size = 0x0004_0000
read = true
write = true
execute = true

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 16384, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
priority = 3
requires = {flash = 16384, ram = 16384 }
stacksize = 2048
start = true

[tasks.gpio]
path = "../../drv/nrf52-gpio/"
name = "drv-nrf52840-gpio"
priority = 2
requires = {flash = 8192, ram = 2048}
start = true
uses = ["gpio0"]

[tasks.blinky]
path = "../../task/blinky"
name = "task-blinky"
priority = 3
requires = {flash = 32768, ram = 2048}
start = true
task-slots = ["gpio"]
