name = "demo-nrf52840-feather"
target = "thumbv7em-none-eabihf"
board = "nrf52840-feather"
chip = "../../chips/nrf52"
stacksize = 896

[kernel]
name = "demo-nrf52840-feather"
requires = {flash = 32768, ram = 4096}
features = ["itm"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.idle]
name = "task-idle"
priority = 6
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.hiffy]
name = "task-hiffy"
priority = 3
max-sizes = {flash = 16384, ram = 16384 }
stacksize = 2048
start = true

[tasks.gpio]
name = "drv-nrf52840-gpio"
priority = 2
features = []
max-sizes = {flash = 4096, ram = 1024}
start = true
uses = ["gpio0"]

# [tasks.blinky]
# name = "task-blinky"
# priority = 4
# max-sizes = {flash = 1024, ram = 1024}
# start = true
# task-slots = ["gpio"]

[tasks.uart]
name = "drv-nrf52-uart"
priority = 3
max-sizes = {flash = 8192, ram = 4096}
start = true
task-slots = ["gpio"]
uses = ["uarte0"]
interrupts = {"uarte0.irq" = 1}

[tasks.rng_driver]
name = "drv-nrf52-rng"
priority = 1
max-sizes = {flash = 16384, ram = 4096}
uses = ["rng"]
start = true
stacksize = 2200

[tasks.aether]
name = "task-aether"
priority = 2
max-sizes = {flash = 131072, ram = 65536 }
stacksize = 32768
start = true
features = ["itm", "log-smoltcp"]
#features = []
uses = ["radio", "ficr", "rng", "clock"]
task-slots = ["rng_driver"]
interrupts = { "radio.irq" = 1 }

[tasks.mqtt]
name = "task-mqtt"
priority = 4
max-sizes = {flash = 65536, ram = 32768 }
start = true
features = ["userlib/log-itm", "userlib/panic-messages"]
task-slots = ["aether", "uart"]
stacksize = 16384

[tasks.air_quality]
name = "task-air-quality"
priority = 5
max-sizes = {flash = 65536, ram = 4096}
start = true
features = ["itm", "userlib/log-itm"]
task-slots = ["i2c_driver"]
stacksize = 1024


[tasks.i2c_driver]
name = "drv-nrf52-i2c"
priority = 4
max-sizes = {flash = 16384, ram = 8192 }
features = ["userlib/log-itm"]
uses = ["twim1"]
start = true
interrupts = {"twim1.irq" = 1}
task-slots = ["gpio"]

[config]
[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.A]
name = "ondevice"

[[config.i2c.controllers.ports.A.pins]]
pins = [ 8, 9 ]
af = 4

[[config.i2c.devices]]
controller = 1
address = 0x77
device = "bme68x"
description = "Bosch air quality sensor"

[config.aether]
pan_id = 0x1eaf
channel = 19

[config.aether.sockets.mqtt]
kind = "tcp"
owner = {name = "mqtt", notification = 1}
tx = { bytes = 2048 }
rx = { bytes = 8192 }

# [config.aether.sockets.throughput]
# kind = "udp"
# port = 2001
# owner = {name = "throughput", notification = 1}
# tx = { packets = 1, bytes = 1024 }
# rx = { packets = 8, bytes = 1024 }
