# Layout from documentation:
#
# https://infocenter.nordicsemi.com/topic/ps_nrf52840/memory.html?cp=4_0_0_3_1_2#memorymap
#
# interrupts from https://docs.rs/nrf52840-pac/latest/nrf52840_pac/enum.Interrupt.html

[ficr]
address = 0x1000_0000
size = 0x1000

[clock]
address = 0x4000_0000
size = 0x1000

[radio]
address = 0x4000_1000
size = 0x1000
interrupts = { irq = 1 }

[rtc0]
address = 0x4000_B000
size = 0x1000
interrupts = { irq = 11 }

[rtc1]
address = 0x4001_1000
size = 0x1000
interrupts = { irq = 17 }

[rtc2]
address = 0x4002_4000
size = 0x1000
interrupts = { irq = 36 }

[uarte0]
address = 0x4000_2000
size = 0x1000
interrupts = { irq = 2 }

[gpio0]
address = 0x5000_0000
size = 0x2000

[rng]
address = 0x4000_D000
size = 0x1000
interrupts = { irq = 13 }

[spim3]
address = 0x4002_F000
size = 0x1000
